upstream hallevault {
  server        hallevault:8080;
}

server {
  listen        80;
  server_name   hallevault.ricardicus.se;

  client_max_body_size 200m;

  location / {
    proxy_pass http://hallevault;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 300s;
  }
}
